andmarti1424/sc-im

- src/Makefile
As per wiki build instructions, to make easier for those building on OS X.
> Added MACOSX build variable and CFLAG

- src/block.c
This is a first try, it translates just one file: `block.c`.
If this change is useful i will translate the rest of the code base.
This PR addresses issue #7
> Translate block.c comments [ #7 ]

- src/cmds.c
- src/cmds.h
- src/cmds_command.c
- src/cmds_insert.c
- src/cmds_normal.c
- src/cmds_visual.c
- src/color.c
- src/file.c
- src/filter.c
- src/help.c
- src/history.c
- src/input.c
- src/macros.h
- src/main.c
- src/maps.c
- src/marks.c
- src/range.c
- src/screen.c
- src/shift.c
- src/sort.c
- src/undo.c
- src/xlsx.c
- src/yank.c
Ok, this translates the whole code base to English so future contributors will be able to help more easily.
This PR solves #7
> Comments translate

- src/cmds.c
- src/cmds.h
- src/cmds_command.c
- src/cmds_insert.c
- src/cmds_normal.c
- src/cmds_visual.c
- src/color.c
- src/file.c
- src/filter.c
- src/help.c
- src/history.c
- src/input.c
- src/macros.h
- src/main.c
- src/maps.c
- src/marks.c
- src/range.c
- src/screen.c
- src/shift.c
- src/sort.c
- src/undo.c
- src/xlsx.c
- src/yank.c
Reverts andmarti1424/sc-im#47.
With latest pull request, sc-im does not compile!
> Revert "Comments translate"

- src/utils/dictionary.c
- src/utils/extra.c
- src/utils/extra.h
- src/utils/string.c
Translate comments from **utils** dir.
Based on `dev` branch.
> Translate utils

- src/doc
Great project!  Appreciate you taking this update.
> Correct spelling of 'quitting' in COMMAND MODE description.

- src/Makefile
- src/cmds_command.c
- src/cmds_visual.c
- src/color.c
- src/file.c
- src/help.c
- src/history.c
- src/input.c
- src/interp.c
- src/main.c
- src/maps.c
- src/range.c
- src/screen.c
- src/sort.c
- src/vmtbl.c
- src/xmalloc.c
> Use pkg-config for ncursesw cflags

- src/doc
The doc needs cleanup: there's inconsistent punctuation and capitalization.
> doc: Corrected trailing spaces and typos.

- src/doc
I'm formatting it in a similar style as the vim help pages.
I'm also rephrasing to clearer English in some cases. Let me know if I misunderstood anything.
Made it about a quarter of the way through. This is a good point to stop and see if this is how you want it.
> Doc formatting

- src/doc
> Format doc: EDIT MODE and COMMAND MODE

- src/doc
> Formatted VISUAL MODE and several more sections.

- src/utils/string.h
> Remove wcwidth and wcswidth declarations

- src/xls.c
https://sourceforge.net/p/libxls/code/HEAD/tree/trunk/libxls/include/libxls/xls.h#l54
> Use preferred function name for xls_close_WB()

- src/cmds_command.c
- src/doc
:file - display the current file name on the status line
:file /some/file - set the current file name to whatever specified
Modeled after vim's file command; in response to #141.
> Add :file command

- src/cmds_command.c
- src/main.c
I made this change in main.c in order to compile on OSX.
Might be useful to other people I guess.
BR,
Paolo Lulli
> Tweak to compile on OSX

- src/Makefile
PR for the patch that the port applies, see:
https://svnweb.freebsd.org/ports/head/math/sc-im/files/patch-Makefile?revision=438936&view=markup
> Fix lua check for FreeBSD

- Readme.md
Hey @andmarti1424, I've decided to consolidate a few Homebrew taps I maintain into one, you can find it here: https://github.com/nickolasburr/homebrew-pfa. This PR is to update the Readme with that information in the Installation section.
> Add updated Homebrew info to Readme

- src/doc
- src/sc-im.1
- src/xlsx.c
Added the --sheet option to pick a sheet when loading an xlsx file
> added xlsx sheet selection

- src/cmds.c
- src/cmds.h
- src/cmds_command.c
- src/doc
- src/gram.y
Coming from libreoffice I though it would be nice to copy multiple rows/columns at once, and since I just saw #312 I'm sending this. This is my second PR and since I'm just 16 I'd appreciate feedback a lot :)
> Expand fcopy's functionality

- src/cmds.c
- src/cmds_command.c
- src/file.c
- src/file.h
> Markdown export with command :e mkd file.md

- src/cmds.c
> no padding for right align str cells

- src/doc
- src/file.c
- src/main.c
> add --export_mkd option

- src/file.c
> fik mkd export not quitting when FILE=null

- src/cmds.c
When using fh to many times the program would crash on a segfault. (see #308)
> Fix issue #308 on github

- src/Makefile
- src/file.c
- src/history.c
- src/main.c
Change the config file location to .config/scimrc and the history file to .cache/sc-iminfo.
> Implement #336

- src/cmds.c
- src/cmds_visual.c
- src/doc
Paste into the visual area. Repeating the yanked area.
p is normal paste
P is like Pc adjust the cell references
addressing the Feature request: Paste to a range of selected cells #438
> Add new command p and P in visual mode.

- src/cmds.c
- src/color.c
- src/color.h
- src/doc
- src/file.c
- src/tui.c
- src/xlsx.c
Italic is supported by xlsxwriter and ncurses (since 5.10 which is now quite old).
> Add italic option to colors

- src/doc
- src/gram.y
- src/main.c
add's VALUEIZEALL,DELETEROW and DELETECOL. I updated the documentation too.
> Pr yacc morescriptcommands

- src/file.c
- src/history.c
Addresses compiler warnings emmitted from my merged pull request.
> Fixed potential buffer overflow in XDG files

- src/cmds.c
Fix for issue #448, as suggested therein.
> fix alignment sensitivity of text overlap

- src/Makefile
- src/cmds_command.c
- src/doc
- src/gram.y
- src/lex.c
> Add visual mode mapping

- src/Makefile
- src/doc
- src/main.c
- src/tui.c
"show_cursor" is the name of the option used with lynx and alpine to
produce the same effect.
> make show_cursor a runtime selectable option

- src/tui.c
Using the column edge isn't clear on a braille display where screen
colors aren't visible, especially with empty cells.
Try to be smarter about cursor location.
This depends on PR #524
> improve cursor placement with show_cursor

- src/Makefile
... such that they are also found if installed to non-standard locations.
> use pkg-config for libxls and libxlsxwriter

- src/cmds.c
- src/cmds_normal.c
- src/cmds_visual.c
- src/macros.h
- src/main.c
- src/tui.c
- src/vmtbl.c
- abstract spreadsheet's available display size
- cleanups to ui_handle_mouse()
- let rescol adjust to the entire range
- improvements to ui_show_sc_col_headings()
> display related fixes

- src/tui.c
Simplify the multi-row display logic.
Don't destroy the `out` array as the code that follows needs it.
Revert to single-row cells when the autowrap config is unset.
> more fix/optimization to the display code

- src/clipboard.c
Especially the computing cost due to repeated get_conf_value()
and strlen().
> simplify the clipboard code a bit

- src/Makefile
> Adjust Makefile to have logic for clipboard commands

- src/Makefile
Reverts andmarti1424/sc-im#631
> Revert "Adjust Makefile to have logic for clipboard commands"

- src/cmds/cmds_command.c
- src/cmds/cmds_normal.c
- src/file.c
- src/file.h
- src/format.c
- src/interp.c
- src/interp.h
- src/lex.c
- src/main.c
- src/main.h
- src/tui.c
- src/xmalloc.c
Hello,
recently I was trying to package this program and came across some issues with building with gcc version 15, so I made few changes to fix the build errors.
If you don't like some of these changes, please tell me what could be improved.
> fix for building with gcc v15
