andmarti1424/sc-im

- src/cmds.c
- src/cmds.h
- src/cmds_command.c
- src/cmds_insert.c
- src/cmds_normal.c
- src/cmds_visual.c
- src/color.c
- src/file.c
- src/filter.c
- src/help.c
- src/history.c
- src/input.c
- src/macros.h
- src/main.c
- src/maps.c
- src/marks.c
- src/range.c
- src/screen.c
- src/shift.c
- src/sort.c
- src/undo.c
- src/xlsx.c
- src/yank.c
Ok, apparently some merge conflicts where unsolved, but after fix them new conflicts appeared relative to master and everything becomes a huge mess.
So here it is again in a new branch: the translations + the corrections were applied and now it compiles.
> Translate comments

- src/cmds_normal.c
- src/conf.c
I have been using sc-im for a while now with no issues.  A couple of days ago I was typing up a column of numbers in numeric mode that I needed summed and noticed that things weren't quite what I expected.
The data was
.5
10
10
.5
.5
.5
.5
Which should be 22.5
But my totals in sc-im showed 45.
I realized I had assumed that decimal points would be treated as such in numeric mode.
So then I thought I'd enter every decimal with a leading 0
That also didnt work - as everytime I hit the '0' it would move the cursor to the leftmost column.
So I created two options --> numeric_zero and numeric_decimal.  When these are each set, the corresponding zero and decimal will initiate numeric entry, but only when numeric mode is also set.
> In numeric mode - treats digit '0' and decimal point '.' as numeric

- src/help.c
`realpath()` can write up to `PATH_MAX` bytes into the provided buffer. From the manpage:
```
The resulting pathname is stored as a null-terminated string, up to a maximum of PATH_MAX bytes, in the buffer pointed to by resolved_path. 
```
Make sure that there is enough space.
Fixes #63.
> Fix realpath() issue

- src/help.c
- src/main.c
Avoid a possible buffer overflow by storing the pointer (which is guaranteed to be in memory for the run of the application) instead of copying the value. This also saves a bit of memory.
> Fix `exename` buffer overflow

- src/file.c
- src/utils/string.c
Fix the `uppercase` function to not depend on undefined behavior.
`sPtr` was used twice in a statement, of which once in a in-place increment - in that case the sequence depends on C compiler, and for many compilers this resulted in removing the first character.
Explicitly delete the first character of the result in `write_fd`, the only callsite.
> Fix uppercase function

- src/xls.c
Unfortunately libxls spells the boolean flag designating whether the cell is
hidden "ishiden" (rather than "isHidden", which would be much better).
> Fixed typo

- src/Makefile
Ah crap, sorry, seems I didn't push the latest version.  Didn't notice that you had separate `LDFLAGS` at first.
> Split pkg-config lines out

- src/doc
was incorrectly marked as c-f instead of c-r
> fix redo key in documentation

- src/Makefile
- src/cmds_command.c
- src/cmds_insert.c
- src/help.c
- src/macros.h
- src/maps.c
Backspace is represented differently on different operating systems. This
was previously addressed with OS flags but even between Linux
distributions and SSH clients the representation can differ.
This commit allows both representations in any build, removing the hack
flag.
> Allow both backspace codes in any build

- src/exec.c
- src/main.c
- src/utils/string.c
- src/utils/string.h
Major issues with split():
1. It allocates too many array entries
2. It will seek into out of bounds memory
3. It seeds to many nulls
See https://github.com/andmarti1424/sc-im/issues/116 for details.
This commit removes split() and replaces its use with some stdlib
functions.
Tests performed:
- ./scim --half_page_scroll   (verify using :set)
- ./scim --half_page_scroll=2 (verify using :set)
- !ls -l
> Remove problematic split() function

- src/dep_graph.c
- src/interp.c
- src/lex.c
Addressing https://github.com/andmarti1424/sc-im/issues/120
As mentioned in Linux's `finite(2)`:
_"Note that these functions are obsolete."_
This commit requires _GNU_SOURCE, or another feature level supporting isfinite() to be defined, i.e. this PR depends on #122
> Replace obsolete finite() calls with isfinite()

- src/Makefile
- src/interp.c
- src/screen.c
- src/utils/string.h
This re-applies the `wcwidth()` and `wcheight()` declaration removal, setting `_GNU_SOURCE` in `CFLAGS`.
`_GNU_SOURCE` is required for:
- `wcwidth()` and `wcswidth()` through `_XOPEN_SOURCE`
- `tm_gmtoff` which is not covered by `_XOPEN_SOURCE`
> Set _GNU_SOURCE (removing wcwidth/wcswidth declarations)

- src/exec.c
- src/file.c
- src/history.c
- src/main.c
(Compiling with GCC 4.8.4 on LXSS/Ubuntu)
- unused results
- incorrect size argument in fgetws
One unused result warning, for dup(), has not been addressed I'm not familiar with its use.
> Address compiler warnings

- src/Makefile
- src/interp.c
- src/lex.c
The variable + `CFLAGS` pattern
FOO = x
CFLAGS := $(CFLAGS) -DFOO=$(FOO)
is replaced by updating `CFLAGS` directly:
CFLAGS += -DFOO=x
This keeps the Makefile a bit shorter and more manageable.
Some other options have been removed because they aren't needed any more, like regex configurations for very old systems and `IEEE_MATH`.
CC is no longer set by the Makefile. It has a default value set by make or the system and can be adjusted in the Makefile or by passing an argument to make: `make CC=clang`
**edit**: forgot to mention, this also removes the OS-specific options and defaults `prefix` to `/usr/local`.
> Simplify Makefile, removing some old options

- src/Makefile
ncurses on macOS only declares `cchar_t` if `_XOPEN_SOURCE_EXTENDED` is defined.
Tested to build on FreeBSD 10.3, macOS 10.11 and Ubuntu trusty.
This addresses the `cchar_t` issue encountered in #126
> _XOPEN_SOURCE_EXTENDED instead of _GNU_SOURCE

- src/xls.c
Contrary to the comment in xls.c, the "isHidden" struct member is actually
spelled "isHidden", even in the latest release version, 1.4.0.
The comment is almost exactly five years out of date now.
Cf. https://sourceforge.net/p/libxls/code/HEAD/tree/trunk/libxls/include/libxls/xlsstruct.h#l430
> Fix XLS importer

- src/Makefile
Both libzip and libXML have pkg-config files. Exploit this fact
to autodetect whether XLSX support may be compiled.
> Autodetect XLSX support

- src/Makefile
The scim binary was looking for `/usr/local/share/scim/SC-IM_help` instead of `/usr/local/share/scim/scim_help`
> Fix mismatched helpfile name in scim binary

- src/doc
A bit of digging in gram.y reveals that color specification to the color
and setcolor commands is actually one argument.
Spell this fact out clearly in the documentation.
> Clarify color and cellcolor arguments

- src/file.c
- src/file.h
- src/main.c
Factor a loadrc() function out of file.c:erasedb(); call it
explicitly after loading a file in main.c:load_sc(). This ensures
$HOME/.scimrc is processed and loaded after the file passed
on the command line is loaded.
Possible fix for #134.
> Process $HOME/.scimrc after loading a file

- src/Makefile
It was declared but not used. The new value reflects the old hardcoded paths.
> Use MANDIR

- src/Makefile
- src/tui.c
Two parts:
1. Fix the build by not using pkg-config if it isn’t available. Some bits of the Makefile were shuffled around to group the rules using pkg-config.
2. A small fix to make sc-im work with macOS’ system ncurses, see #159 
To test a vanilla macOS build if Homebrew is installed:
PATH=/usr/bin:/bin make
To test against Homebrew ncurses, which is keg-only to prevent clashing with system ncurses:
brew install ncurses
PKG_CONFIG_PATH=/usr/local/opt/ncurses/lib/pkgconfig make
> Fix vanilla (non-Homebrew) Mac

- Readme.md
- src/Makefile
Removing the unneeded dependency on Homebrew ncursesw, as macOS system
ncurses also includes wide character support and is compatible with sc-im.
System ncurses is already used for the vanilla build:
https://github.com/andmarti1424/sc-im/pull/183
> Always use system ncurses on macOS

- Readme.md
- src/Makefile
Dear Andrés,
Here is a `Makefile` with a couple of lines added for improved GNU/Linux support.
I have also added Ubuntu installation instructions to the `Read.me`.
These instructions will only work with the patched `Makefile`.
With the Ubuntu instructions on a prominent place (the Wiki is often overlooked by many), I hope a whole lot more people will start using sc-im.
> Makefile and installation instructions for Ubuntu.

- Readme.md
* Consistent style
* Use markdown backticks for commands and paths
* Remove extraneous '/' prefix from paths
* Link to src/Makefile
* Use `make -C src`
* Binary is named `scim`, not `sc-im`
> Improve manual installation section

- Readme.md
- src/Makefile
- src/doc
- src/file.c
```sh
mkdir sc-im-test
cd sc-im-test
mkdir lua
echo 'function trg(c,r)' >> lua/test.lua
echo '  sc.lsetstr(1,1,"String From Lua")' >> lua/test.lua
echo '  sc.sc("LET A2=5")' >> lua/test.lua
echo 'end' >> lua/test.lua
echo 'set external_functions' >> test.sc
echo 'trigger a5 "mode=W type=LUA file=test.lua function=trg"' >> test.sc
echo 'goto A1' >> test.sc
```
Open `path/to/sc-im test.sc` and change cell A5. This will trigger the lua script to run.
In order to get Lua support working on OS X, the compiler flags needed to be changed slightly. `-Wl,--export-dynamic` is not supported, `-rdynamic` must be used instead.
> Allow for lua scripts in local .sc directory

- src/macros.h
- src/pipe.c
- src/tui.c
Currently, the non-interactive mode outputs to standard output (or output file) both informational messages and calculated values (getnum, getfmt).
This PR separates those two types, and send only calculated values to output while sending to standard error the informational messages.
> Send informational messages to stderr rather than the output when used in non-interactive mode

- src/Makefile
If `pkg-config` wasn't available `ncurses` would only be linked on macOS. This commit adds a fallback case to link `ncursesw` by default.
> Link ncursesw by default if not using pkg-config

- src/Makefile
- src/cmds_command.c
- src/file.c
- src/main.c
This PR adds OpenBSD support.
The main obstacle is OpenBSD's [lack](http://openbsd-archive.7691.n7.nabble.com/patch-libc-wordexp-support-td159368.html) of `wordexp()`. This is handled by adding support for a `NO_WORDEXP` macro. When defined (only on OpenBSD for now), shell expansion is simply skipped.
The only other change is not adding `-ldl`, as on FreeBSD.
> OpenBSD support (mostly wordexp() workaround)

- src/cmds.c
Happened to me before I read  up how fcopy actually worked, and while not many people will come across this case I still think it'd be nice to display a proper error. 3rd PR from a 16 year old, so please be gentle with your feedback :)
> Fix segfault when fcopy'ing with no selection while on first column

- src/file.c
Fixes #317 by making `fg` and `bg` parameters of `cellcolor` optional so the save output is correct.
> Fix cellcolor file output for empty colors

- src/doc
- src/file.c
- src/main.c
Adds command line options: `--export_csv`, `--export_tab`, `--export_txt` and `--export`, synonymous with `--export_txt`.
There needs to be a way to convert `.sc` files to text form, without having to manually enter the command in the UI or to fake the _curses_ environment. Also separately requested in #359.
Notably, with this fix, one can add the following to `.gitattributes`
```
*.sc diff=scim
```
and
```
[diff "scim"]
textconv = sc-im --quit_afterload --nocurses --export
cachetextconv = false
```
in `.gitconfig` and get visual diffs of the spreadsheets.
> command line option to export

- .gitignore
- doc/grammar_yacc_tools/Makefile
- doc/grammar_yacc_tools/README.md
- doc/grammar_yacc_tools/y2l
- doc/grammar_yacc_tools/y2l.license
- doc/grammar_yacc_tools/y2l.readme
- examples/nocurses/export_to_mkd.sc
- examples/nocurses/nocurses.readme
- examples/xlsx/xlsx2markdown.sc
- src/cmds_command.c
- src/doc
- src/file.c
- src/gram.y
- src/main.c
New summary:
- merge #381 (doc about markdown export)
- add tools for generating command lists from gram.y to be used in src/doc
- updated ./src/doc
- format cleanup (wrap too long lines)
- add the EXECUTE command in gram.y for no interactive scripting
- add documentation and examples
- resolved conflicts with #360
> Add execute command and documentation update

- src/conf.c
- src/main.c
- src/main.h
The grep command I used to search for options in the code is included in main.c
```
$ sc-im --help
SC-IM - SC Improved
Usage: sc-im [arguments] [file]          specified file
or: sc-im [arguments] -               read text from stdin
Arguments:
--autocalc                  Set variable 'autocalc'.
--copy_to_clipboard_delimited_tab  Set variable 'copy_to_clipboard_delimited_tab'
--debug                     Set variable 'debug'
--default_copy_to_clipboard_cmd=COMMAND  set variable 'default_copy_from_clipboard_cmd'
--default_paste_from_clipboard_cmd=COMMAND  set variable 'default_paste_from_clipboard_cmd'
--export_csv                Export to csv without interaction
--export_tab                Export to tab without interaction
--export_txt                Export to txt without interaction …
```
> add --help option

- src/cmds_command.c
When I do ```:wq``` I get ```Failed expanding filepath```. This fixes this.
> fix wq alias for x command

- src/Makefile
Prevents 'install' from adding a +x bit.
This is a patch from the pkgsrc work (#303).
> Install data files with permissions 644

- src/Makefile
Using `test -f y.tab.c && mv ...` in the Makefile causes `make`
to exit with a non-zero exit code in case the file does not exist.
This can lead to issues with automating builds.
> Avoid using `&&` in Makefile

- src/cmds.c
- src/cmds_command.c
- src/cmds_normal.c
- src/cmds_visual.c
- src/color.c
- src/color.h
- src/filter.c
- src/filter.h
- src/input.c
- src/tui.c
In gcc 10, -fno-common is now default, disabling merging of same-name variables declared in different places. To correct it, declarations must be explicitly extern, and definitions must be in only one place. In sc-im this applies to variables declared in .h files, such as interp_line and ucolors.
> Mark array declarations extern to work with gcc 10 -fno-common

- src/conf.c
- src/doc
- src/gram.y
- src/tui.c
Display current file name along with the normal/edit mode currently displayed at top right.
When multiple spreadsheets are simultaneously being worked on in different windows, it can become hard to tell which is which. Often, I keep a `before` version open in a separate window for reference, and don't want to change that version inadvertently. The mistakes can be reverted of course, and tracked say with _git_, but this goes to simple efficiency and usability.
Symlink a test spreadsheet say to `very_very_very_very_long_long_long_name_name_name.sc`, open it with `sc-im` in a very small terminal window. No crashes, filename is displayed, gets overwritten white editing a cell content, but comes right back.
> Show filename in status

- src/file.c
- src/interp.c
This PR fixes three issues with writing colours to files, the first two of which were introduced in 1dcf37b1.
First, a color with no `bg` or `fg` but multiple modifiers would be saved as e.g. `bold=1underline=1`.
Second, if `fg` or `bg` were `DEFAULT_COLOR`, this would never be saved because 1dcf37b1 treated `DEFAULT_COLOR` and `NONE_COLOR` as the same. I don't understand why there needs to be a difference, but the rest of the program clearly treats them as different. The fix for this modifies the `decompile` function; I am not sure if this goes against the idea of the function somehow, but it seems to work.
Third, empty cellcolor strings would sometimes be saved (such as `cellcolor A1:A2 ""`).
> Fix issues when writing colour information to a file

- src/gram.y
- src/interp.c
- src/sc.h
Resolves #468
It's accurate until you try to do 23!, I'm not sure how to store numbers more precise than double, if you do 2^128 in sc-im it calculates fine.
> Add factorial function

- src/file.c
This pull request fixes #405. Since there would have been duplicated code to get the delimiter for each function, a get_delim function was added. The original code for handling delimiters only handles ; , \t so this was preserved in the function. A future pull request can make the delimiter more flexible.
> Fix issue #405 by making function for get_delim

- src/main.c
Currently when stdin is given is overwrites the file contents. This PR enables sc-im to load a file and afterwards apply commands from stdin. I needed to fix a problem at 579 to make this work.
Here's an example how to use it. [demo.sc.zip](https://github.com/andmarti1424/sc-im/files/4182375/demo.sc.zip)
(PR #390 with the extra command's is needed for this to work)
```
echo "VALUEIZEALL\nDELETECOL C\n" |sc-im  --nocurses --export_mkd --quit_afterload demo.sc
```
> read stdin after file loading

- src/Makefile
- src/file.c
- src/history.c
This closes #358.
This pull request changes default configuration and history file finding behaviour. In short:
* **BREAKING** - In the Makefile, `CONFIG_DIR` is set to `~/.config/sc-im/` by default. This means that `scimrc` must instead be placed in `~/.config/sc-im/scimrc` by default.
* The hardcoded path in `plugin_exists` has been removed, and sc-im will search for plugin files in `CONFIG_DIR` or in `$XDG_CONFIG_HOME/sc-im`. It should still search the old hardcoded path `~/.scim` for compatibility reasons, but this should probably be deprecated.
* If `$XDG_CONFIG_HOME` or `$XDG_CACHE_HOME` are set, sc-im will ignore the `CONFIG_DIR` and `HISTORY_DIR` set at compile time. `CONFIG_DIR` effectively becomes `$XDG_CONFIG_HOME/sc-im`, while `HISTORY_DIR` has no change from default …
> Add full XDG Base Specification compliance

- src/Makefile
This commit makes with libxls (libxlsreader) the same that is done with libxlsxwriter: to automatically detect the presence of the library and use it in case the system provides it.
> automatically use libxls (libxlsreader) if it is present

- src/help.c
- src/tui.c
This is especially useful for blind people using braille displays.
A braille display is a device with mechanical dots representing the
content of the screen in braille with the aid of a software package
such as BRLTTY. Those displays are made of a single line with a variable
number of rows depending on the model, usually 40 or 80. This is
effectively a 1x40 window view of the screen.
By default, the braille window moves with the position of the screen
cursor. It doesn't track attributes such as reverse color as this is
too unreliable. Finding the actual active cell manually is a daunting
task.
This patch makes sc-im locate the cursor in the active cell when
navigating around so the braille window can automatically be located
on the active cell, or on the input field when active, or on the …
> move (invisible) cursor to the active grid cell

- src/tui.c
The centering of the column header is done by padding with spaces on the
left. This padding is at least one space. This breaks the header display
when a column width is set to 2 and the header is a double-letter as the
second letter overflows the field and gets overwritten.
Rework the padding computation so that double-letter headings are always
properly centered, including in the extreme case with a width of 2 where
no padding at all should be applied.
This also properly aligns single-letter headers with centered single-letter
cell content when the field width is odd.
> fix column header display

- src/clipboard.c
- src/cmds.c
- src/cmds_command.c
- src/cmds_normal.c
- src/color.c
- src/conf.c
- src/conf.h
- src/file.c
- src/gram.y
- src/input.c
- src/interp.c
- src/main.c
- src/shift.c
- src/tui.c
- src/utils/dictionary.c
- src/utils/dictionary.h
- src/xlsx.c
Those are changes that are certainly going to improve performance
and make the code easier to understand.
> many improvements to the config facility and usage

- src/conf.c
- src/main.c
- src/utils/dictionary.c
- src/utils/dictionary.h
I didn't notice that multiple key=value pairs were possible in a single
string. Here's a new implementation that does it, with the ability to
parse the whole default_config string as well as command line args.
> fix dictionary string parser

- examples/markdown/markdown-table-alignment.md
- examples/markdown/markdown-table.md
- src/doc
- src/file.c
- src/file.h
Refreshed version of an old PR branch. Ready to merge.
- sc-im can now import .mkd files
- when current file is .mkd is writes to .mkd format
- markdown column alignment is respected.
- doc and help are updated
When this is merged https://github.com/mipmip/vim-scimark should work with the vanilla sc-im
> .mkd import, read write mardown, update docs

- src/tui.c
- src/tui.h
The displaying of a row may have its height dynamically adjusted.
When that happens, the number of displayable rows may no longer be
correct, leading to currow being located outside of the screen.
Let's work around this issue by redrawing the screen in that case after
all potentially displayable rows had their height validated.
Fixes #578.
> recalculate number of mobile rows if row height changes during display

- src/cmds/cmds.c
If one follows the sequence in issue #578 (which is now fixed) the
selected cell ends up on row 33. But moving to row 34 will leave
4 empty lines at the bottom of the screen.
Fix that by attempting to fill up the screen when there is still room
after counting rows/cols in the backward case.
Also fix the returned "last" row/col in calc_mobile_rows() and
calc_mobile_cols() to always be the last one to fit on screen.
even in the backward case.
> adjust row/col count on edge cases

- src/file.c
At the moment, following links / opening files from cells with ampersands, spaces, etc. doesn't work as expected for obvious reasons.
e.g. `https://example.com/?a&shutdown now` (less contrived examples do exist).
Thanks.
> Pass cell contents correctly when following links

- src/doc
- src/gram.y
Not sure if this was a deliberate omission or just an oversight. Either way I think it's useful to be able to change this without recompiling (e.g. desktop users might prefer xdg-open).
I've copied how this works from default_copy_to_clipboard_cmd, which seems to work fine.
> Allow changing default_open_file_under_cursor_cmd at runtime

- src/main.c
This PR rearranges the order of `load_rc` and `load_file` and also removes some related redundant checks.
Related issue: #778
> Make passing a file on command line consistent with :load with regards to loading configuration

- src/conf.c
- src/doc
- src/gram.y
- src/input.c
This option allows to always go from input to edit mode when pressing ESC.
See #620
> add input_edit_mode setting

- src/formats/ods.c
I went to install this program on my arch machine and saw compilation had failed. Seemed that ods.c was missing an include for the free() calls.
> fixed compiler error related to missing include

- src/Makefile
This resolves #767, but only for macOS.
The ncurses brew package installs a pkg-config file for ncursesw, so it works properly when there is no special case for Darwin in terms of setting CFLAGS and LDLIBS.
> Modifies Makefile to work with brew's ncurses on macOS

- src/interp.c
IF: case in `seval` calls `eval` with `ent` set to NULL which allways causes an error message and an incorrect dep graph
see issue #910
> fix spurious error message with @IF command issue #910

- src/function.c
- src/interp.c
- tests/test-replace.sh
Fix for memory leak, seg fault and infinite loop in `@replace`
see issue #912
> fix: memory leak and segfault in @replace (issue #912)

- src/function.c
- tests/test-replace.sh
Recent PR fixing a crash in replace failed to take account of possible NULL second argument.
(issue #919)
Testing also revealed a segfault in `sevaluate` if the input is invalid.
> fix crashes in replace (from recent patch) and sevaluate (issue #919)
